server:
  port: 8082

spring:
  datasource:
    username: root
    password: OorwdAS8
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/ape-frame?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf8&useSSL=false
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      initial-size: 20
      min-idle: 20
      max-active: 100
      max-wait: 60000
      stat-view-servlet:
        enabled: true
        url-pattern: /druid/*
        login-username: admin
        login-password: 123456
      filter:
        stat:
          enabled: true
          log-slow-sql: true
          slow-sql-millis: 2000
        wall:
          enabled: true
redis:
  host: 127.0.0.1
  port: 6379
  database: 0
  # 可以基于lettuce，也可以基于jedis
  lettuce:
    pool:
      max-active: 20 # 最大连接数
      min-idle: 0 # 最小空闲连接数
      max-idle: 8 # 最大空闲连接数
      max-wait: -1 # 最大等待时间，-1表示无限期等待
sql:
  beauty:
    show: false

mybatis-plus:
  global-config:
    db-config:
      logic-delete-field: delete_flag
      logic-delete-value: 1
      logic-not-delete-value: 0
init:
  cache:
    enable: true

# Swagger配置
swagger:
  base-package: com.ape.user.controller # 通常扫描controller包
  title: ape-sys API文档
  description: ape-sys的RESTful API文档
  contact:
    name: 李良杰
    url: https://github.com/liliangjiep/ape-frame.git
    email: someone@qq.com
  version: 1.0

logging:
  config: classpath:log4j-spring.xml

log:
  aspect:
    enable: true